name: FIRST #название
on: [push] # тригер запуска

env:
  NODE_ENV: production
  TEST_ENV: ${{ vars.DOCKER_USERNAME }} #достаем обычную переменную из гитхаба и устанавливаем ее в TEST_ENV
  TEST_SECRET: ${{ secrets.DOCKER_TOKEN }} #достаем переменную из секрета гитхаба и устанавливаем ее в TEST_SECRET

jobs:
  build: #название джобы
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Display environment variables
        run: | #через знак $ обращаемся к любой пеерменной из env
          echo NODE_ENV is $NODE_ENV
          echo TEST_ENV is $TEST_ENV
          echo TEST_SECRET is $TEST_SECRET
